# Generated by Django 6.0.4 on 2026-04-17 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_libros', '0002_genero_libros_genero'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genero',
            new_name='Generos',
        ),
    ]
